import React from 'react';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import './globals.css';
import { ConfigProvider } from 'antd';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang="en">
		<body className={inter.className}>
			<StyledComponentsRegistry>
				<ConfigProvider
					theme={{
						token: {
							// colorPrimary: '#00b96b',
						},
						components: {
							Switch: {
								handleShadow: '0 2px 4px 0 rgba(255, 255, 255, 0.7)',
								// handleBg: 'blue',
							},
						},
					}}
				>
					{children}
				</ConfigProvider>
			</StyledComponentsRegistry>
		</body>
	</html>
);

export default RootLayout;
